CC     :=  gcc
CFLAGS := -Wall -Wextra -std=c11 -D_POSIX_C_SOURCE=200809L
LDLIBS  = -lpcap

TARGET := ScanTest
SRC    := ScanTest.c
OBJ    := $(SRC:.c=.o)

.PHONY: main clean

main: clean $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)
